// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/appspecific/com.tesla.3p.public-key.pem": {
            "get": {
                "description": "Returns the EC public key PEM used for Tesla Fleet API partner registration. Tesla fetches this endpoint unauthenticated.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "fleet"
                ],
                "summary": "Serve Fleet API EC public key",
                "responses": {
                    "200": {
                        "description": "PEM-encoded EC public key",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "public key not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns OK when the HTTP process is running.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/oauth/callback": {
            "get": {
                "description": "Exchanges the authorization code for tokens and stores them encrypted in SQLite.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Handle Tesla OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth state parameter",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OAuth successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "missing state, code, or cookie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "exchange or persistence error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/oauth/start": {
            "get": {
                "description": "Redirects the user to Tesla's OAuth authorization page. Sets a state cookie for CSRF protection.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Start Tesla OAuth flow",
                "responses": {
                    "302": {
                        "description": "Redirect to Tesla OAuth",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tesla Charging Monitor",
	Description:      "Nightly charging monitor. HTTP endpoints support Tesla OAuth, Fleet registration, and health checks.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
